package fit5170.assignment;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.InetAddress;
import java.net.Socket;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 * SWING based client GUI for 3 step of hotel booking process
 * This frame allows the client to enter their personal details
 * and submit the booking (after already having selected a hotel and room)
 * @author Bhavik Maneck
 */
public class ClientJFrame extends javax.swing.JFrame {
    
    /**
     * Socket and message objects are kept as class members to
     * allow a generic method, setupBrokerConnection(), to be called 
     * to setup connection whenever some method needs to talk with the Broker
     */ 
    private Socket server;
    private InetAddress address;
    private BufferedReader reader;
    private DataOutputStream os;
    private DataInputStream is;
    private PrintStream writer;
    
    Date checkIn;
    Date checkOut;
    
    /**
     * Creates new form ClientJFrame with preset information from first 
     * two steps of booking
     */
    public ClientJFrame(String selectedHotelName, String selectedCity, 
                        Date selectedCheckIn, Date selectedCheckOut, 
                        String Room, String noRooms, String total) {
        initComponents();
        
        jTextFieldCity.setText(selectedCity);
        jTextFieldHotel.setText(selectedHotelName);
        jTextFieldRoom.setText(Room);
        jTextFieldRooms.setText(noRooms);
        jTextFieldTotal.setText(total);
        
        checkIn = selectedCheckIn;
        checkOut = selectedCheckOut;
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        jTextFieldCheckIn.setText(formatter.format(checkIn));
        jTextFieldCheckOut.setText(formatter.format(checkOut));
        
        //Disable already filled out fields, just shown for information purposes to user
        jTextFieldCity.setEnabled(false);
        jTextFieldHotel.setEnabled(false);
        jTextFieldRoom.setEnabled(false);
        jTextFieldRooms.setEnabled(false);
        jTextFieldTotal.setEnabled(false);
        jTextFieldCheckIn.setEnabled(false);
        jTextFieldCheckOut.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldCreditCard = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldHotel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRoom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldRooms = new javax.swing.JTextField();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCheckIn = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCheckOut = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel6.setText("Hotel Booking System - Book Room");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldLastName.setMinimumSize(new java.awt.Dimension(150, 28));
        jTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastNameActionPerformed(evt);
            }
        });

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });

        jTextFieldCreditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCreditCardActionPerformed(evt);
            }
        });

        jButtonBack.setText("< Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Email:");

        jLabel4.setText("Phone Number:");

        jLabel5.setText("Credit Card No:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel7.setText("Hotel Booking System - Book Room");

        jLabel8.setText("City:");

        jTextFieldCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCityActionPerformed(evt);
            }
        });

        jLabel9.setText("Hotel:");

        jTextFieldHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHotelActionPerformed(evt);
            }
        });

        jLabel10.setText("Room:");

        jTextFieldRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRoomActionPerformed(evt);
            }
        });

        jLabel11.setText("No. Rooms:");

        jTextFieldRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRoomsActionPerformed(evt);
            }
        });

        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });

        jLabel12.setText("Total Price:");

        jTextFieldCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCheckInActionPerformed(evt);
            }
        });

        jLabel13.setText("Check In:");

        jTextFieldCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCheckOutActionPerformed(evt);
            }
        });

        jLabel14.setText("Check Out:");

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(45, 45, 45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(jTextFieldEmail)
                                            .addComponent(jTextFieldPhone)
                                            .addComponent(jTextFieldCreditCard))
                                        .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBack)
                                .addGap(37, 37, 37)
                                .addComponent(jButtonSubmit))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(15, 15, 15)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldTotal)
                            .addComponent(jTextFieldRooms)
                            .addComponent(jTextFieldCheckIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jTextFieldRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonSubmit))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jTextFieldCreditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCreditCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCreditCardActionPerformed

    private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastNameActionPerformed
    
    //Go back to previous booking window (choose hotel room)
    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        //Close this frame
        dispose();
        
        //Relaunch rooms frame with its already filled out information
        RoomsJFrame roomWindow = new RoomsJFrame(jTextFieldHotel.getText(),
                                                 jTextFieldCity.getText(),
                                                 checkIn,
                                                 checkOut,
                                                 jTextFieldRoom.getText(),
                                                 jTextFieldRooms.getText());
        roomWindow.setVisible(true);
            
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCityActionPerformed

    private void jTextFieldHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHotelActionPerformed

    private void jTextFieldRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRoomActionPerformed

    private void jTextFieldRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRoomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRoomsActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jTextFieldCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCheckInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCheckInActionPerformed

    private void jTextFieldCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCheckOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCheckOutActionPerformed
    
    //Booking has been submitted
    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        setupBrokerConnection();
        
        //Get all the client information for validation and submitting
        //to server (via broker)
        String firstName = jTextFieldFirstName.getText();
        String lastName = jTextFieldLastName.getText();
        String email = jTextFieldEmail.getText();
        String phone = jTextFieldPhone.getText();
        String creditCard = jTextFieldCreditCard.getText();
        
        //For validation, send client info JSON to broker
        String requestType = "VALIDATE";
        String requestName = "client";
        JSONObject validationJson = new JSONObject();
        validationJson.put("request_type", requestType);
        validationJson.put("request_name", requestName);
        validationJson.put("first_name", firstName);
        validationJson.put("last_name", lastName);
        validationJson.put("email", email);
        validationJson.put("phone", phone);
        validationJson.put("creditCard", creditCard);
        
        //Send the JSON to Broker
        writer.println(validationJson);
        
        //Get back JSON response from Broker
        JSONObject brokerValidationJsonResponse = new JSONObject();
        try {
            brokerValidationJsonResponse = new JSONObject(reader.readLine());
        } catch(IOException e) {
            System.out.println(e);
        }
        System.out.println(brokerValidationJsonResponse.toString()); //for debug
        
        if (brokerValidationJsonResponse.getBoolean("error")) { //Error in client info validation
            
            //Build up the error message for each field
            String errorMessagesToShow = "";
            
            if (!brokerValidationJsonResponse.getString("error_first_name").equalsIgnoreCase("None"))
            {
                errorMessagesToShow += brokerValidationJsonResponse.getString("error_first_name");
                errorMessagesToShow += "\n";
            }
            if (!brokerValidationJsonResponse.getString("error_last_name").equalsIgnoreCase("None"))
            {
                errorMessagesToShow += brokerValidationJsonResponse.getString("error_last_name");
                errorMessagesToShow += "\n";
            }
            if (!brokerValidationJsonResponse.getString("error_email").equalsIgnoreCase("None"))
            {
                errorMessagesToShow += brokerValidationJsonResponse.getString("error_email");
                errorMessagesToShow += "\n";
            }
            if (!brokerValidationJsonResponse.getString("error_phone").equalsIgnoreCase("None"))
            {
                errorMessagesToShow += brokerValidationJsonResponse.getString("error_phone");
                errorMessagesToShow += "\n";
            }
            if (!brokerValidationJsonResponse.getString("error_credit_card").equalsIgnoreCase("None"))
            {
                errorMessagesToShow += brokerValidationJsonResponse.getString("error_credit_card");
                errorMessagesToShow += "\n";
            }
            
            //Display the error message
            JOptionPane.showMessageDialog(null, errorMessagesToShow);
            
        } else { //Proceed with submitting booking
            
            setupBrokerConnection();
            
            //Setup 'header' of JSON object for submitting booking data
            String bookingRequestType = "POST";
            String bookingRequestName = "booking";
            JSONObject obj = new JSONObject();
            obj.put("request_type", bookingRequestType);
            obj.put("request_name", bookingRequestName);

            //Add new client information for submission
            obj.put("first_name", firstName);
            obj.put("last_name", lastName);
            obj.put("email", email);
            obj.put("phone", phone);
            obj.put("creditCard", creditCard);

            //Add hotel information for submission
            obj.put("city", jTextFieldCity.getText());
            obj.put("hotel", jTextFieldHotel.getText());
            obj.put("room", jTextFieldRoom.getText());
            obj.put("rooms", jTextFieldRooms.getText());
            obj.put("check_in", jTextFieldCheckIn.getText());
            obj.put("check_out", jTextFieldCheckOut.getText());

            //Send the JSON booking submission to Broker
            writer.println(obj);

            JSONObject brokerJsonResponse = new JSONObject();
            try {
                brokerJsonResponse = new JSONObject(reader.readLine());
            } catch(IOException e) {
                System.out.println(e);
            }

            System.out.println(brokerJsonResponse.toString()); //for debug

            //Check the response from the Broker (and Server)
            String result = brokerJsonResponse.getString("results");
            if (result.equals("success"))
            {
                JOptionPane.showMessageDialog(null, "Booking success!");

                //Close this window now that booking was a success and go back to start
                dispose();
                MainJFrame mainWindow = new MainJFrame();
                mainWindow.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Booking failed.");
            }
        
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed
    
    //Used by action listeners and other setup methods that need data
    //to populate the view to setup connection to Broker to request information
    //or submit data
    private void setupBrokerConnection() {
        
        try {
            address = InetAddress.getByName("localhost");
            server = new Socket(address, 8000);

            os = new DataOutputStream(server.getOutputStream());
            is = new DataInputStream(server.getInputStream());
            reader = new BufferedReader(new InputStreamReader(is));
            writer = new PrintStream(os);
        } catch(Exception e) {
            e.printStackTrace();   
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldCheckIn;
    private javax.swing.JTextField jTextFieldCheckOut;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCreditCard;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldHotel;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldRoom;
    private javax.swing.JTextField jTextFieldRooms;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
